# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [2]:
#1
print("Shape:")
print(df.shape)
print("\nColumn Names:")
print(df.columns)

#2
print("\nBasic Information:")
print("Total Array Elements:", df.size)
print("Maximum Age:", df["Age"].max())
print("Minimum Age:", df["Age"].min())
print("Average Age:", df["Age"].mean())
print("Median Age:", df["Age"].median())
print("Standard Deviation of Age:", df["Age"].std())
print("Maximum Fare:", df["Fare"].max())
print("Minimum Fare:", df["Fare"].min())
print("Average Fare:", df["Fare"].mean())
print("Median Fare:", df["Fare"].median())
print("Standard Deviation of Fare:", df["Fare"].std())
print(df["Sex"].value_counts())
print(df["Survived"].value_counts())
print(df["Pclass"].value_counts())
print(df["Embarked"].value_counts())
print(df["SibSp"].value_counts())

#3
print("\nFirst 10 Rows:")
print(df.head(10))

Shape:
(891, 12)

Column Names:
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Basic Information:
Total Array Elements: 10692
Maximum Age: 80.0
Minimum Age: 0.42
Average Age: 29.69911764705882
Median Age: 28.0
Standard Deviation of Age: 14.526497332334044
Maximum Fare: 512.3292
Minimum Fare: 0.0
Average Fare: 32.204207968574636
Median Fare: 14.4542
Standard Deviation of Fare: 49.693428597180905
Sex
male      577
female    314
Name: count, dtype: int64
Survived
0    549
1    342
Name: count, dtype: int64
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
SibSp
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64

First 10 Rows:
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                              Heikkinen, Miss Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750   NaN        S
8      2            347742  11.1333   NaN        S
9      0            237736  30.0708   NaN        C

**Explanation**

I used numpy shape to print out the number of rows and columns in the dataset. I used columns to print out the label of each column.

For basic information, I included minimum and maximum values, mean, average, and standard deviations for some important values in the dataset. I also included counts of categories for certain columns that might be valuable information.

I used head to print out the first ten rows of the dataset.

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [3]:
#1
df["Name"]

#2
df["Age"]
df["Cabin"]
df["Fare"]

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [4]:
#3
df.loc[66]

PassengerId                              67
Survived                                  1
Pclass                                    2
Name           Nye, Mrs. (Elizabeth Ramell)
Sex                                  female
Age                                    29.0
SibSp                                     0
Parch                                     0
Ticket                           C.A. 29395
Fare                                   10.5
Cabin                                   F33
Embarked                                  S
Name: 66, dtype: object

**Explanation**

Select row 66 of the dataset using loc.

In [5]:
#4
df.loc[60:70, 'PassengerId':'Name']

    PassengerId  Survived  Pclass                            Name
60           61         0       3           Sirayanian, Mr. Orsen
61           62         1       1              Icard, Miss Amelie
62           63         0       1     Harris, Mr. Henry Birkhardt
63           64         0       3            Skoog, Master Harald
64           65         0       1           Stewart, Mr. Albert A
65           66         1       3         Moubarek, Master Gerios
66           67         1       2    Nye, Mrs. (Elizabeth Ramell)
67           68         0       3        Crease, Mr. Ernest James
68           69         1       3  Andersson, Miss Erna Alexandra
69           70         0       3               Kink, Mr. Vincenz
70           71         0       2      Jenkin, Mr. Stephen Curnow

**Explanation**

Used slicing to select a range within the data. Shows rows 60-70 and columns PassengerID to Name.

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [6]:
#1
ageOverSixty = df[df['Age'] > 60]
display(ageOverSixty)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

**Explanation**

Used boolean indexing to only display rows where passenger is over 60 years old. Code returns rows where the condition is true, in this case >60.

In [7]:
#2
fareOverOneHundred = df[(df['Fare'] > 100) & (df['Pclass'] == 1)]
display(fareOverOneHundred)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

**Explanation**

Used boolean indexing to display rows where the specified conditions are true: fare is > 100 and passenger is in first class.

In [8]:
#3
nullAge = df[df['Age'].isnull()]
display(nullAge)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

**Explanation**

Identifies rows where age is null by selecting the Age column and using isnull(), assigns these rows to variable nullAge. Then displays rows with a null age.

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [9]:
#1
reversed = df.reindex(index=df.index[::-1])
display(reversed)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

**Explanation**

Using reindexing to reverse the order of the rows. df.index gives the the row indices and [::-1] reverses the order. Then reindex rearranges the rows.

In [10]:
#2
oneColumnRemoved = df.drop(columns = ["SibSp"])
display(oneColumnRemoved)

,PassengerId,Survived,Pclass,Name,Sex,Age,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,370376,7.7500,NaN,Q

**Explanation**

Use df.drop() to remove a specified column.

In [11]:
#3
noNullAge = df.dropna(subset = ["Age"])
display(noNullAge)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

**Explanation**

Used dropna which is specific to dropping rows with missing values. Identifies null entries and drops those rows.

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [12]:
#1
df['Fare (Euros)'] = df['Fare'] * 0.86
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare (Euros)
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,11.180000
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,25.800000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,20.167000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.800000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,6.665000

**Explanation**

Create new column using df['Fare (Euros)'], then multiply the original fares in USD by the conversion rate of 0.86.

In [13]:
#2
partFiveDf= df.copy()

partFiveDf['Age'] = partFiveDf['Age'] - partFiveDf['Age'].mean()
display(partFiveDf)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare (Euros)
0,1,0,3,"Braund, Mr. Owen Harris",male,-7.699118,1,0,A/5 21171,7.2500,NaN,S,6.235000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,8.300882,1,0,PC 17599,71.2833,C85,C,61.303638
2,3,1,3,"Heikkinen, Miss Laina",female,-3.699118,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,5.300882,1,0,113803,53.1000,C123,S,45.666000
4,5,0,3,"Allen, Mr. William Henry",male,5.300882,0,0,373450,8.0500,NaN,S,6.923000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,-2.699118,0,0,211536,13.0000,NaN,S,11.180000
887,888,1,1,"Graham, Miss Margaret Edith",female,-10.699118,0,0,112053,30.0000,B42,S,25.800000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,20.167000
889,890,1,1,"Behr, Mr. Karl Howell",male,-3.699118,0,0,111369,30.0000,C148,C,25.800000
890,891,0,3,"Dooley, Mr. Patrick",male,2.300882,0,0,370376,7.7500,NaN,Q,6.665000

**Explanation**

Copied the dataset so that the original does not get affected. Reassign the values in the age column to the original age minus the mean of all ages, then display the new data.

In [14]:
#3
partFiveDf[["Age", "Fare"]] = partFiveDf[["Age", "Fare"]] - np.array([1, 6])
display(partFiveDf)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare (Euros)
0,1,0,3,"Braund, Mr. Owen Harris",male,-8.699118,1,0,A/5 21171,1.2500,NaN,S,6.235000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,7.300882,1,0,PC 17599,65.2833,C85,C,61.303638
2,3,1,3,"Heikkinen, Miss Laina",female,-4.699118,0,0,STON/O2. 3101282,1.9250,NaN,S,6.815500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,4.300882,1,0,113803,47.1000,C123,S,45.666000
4,5,0,3,"Allen, Mr. William Henry",male,4.300882,0,0,373450,2.0500,NaN,S,6.923000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,-3.699118,0,0,211536,7.0000,NaN,S,11.180000
887,888,1,1,"Graham, Miss Margaret Edith",female,-11.699118,0,0,112053,24.0000,B42,S,25.800000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,17.4500,NaN,S,20.167000
889,890,1,1,"Behr, Mr. Karl Howell",male,-4.699118,0,0,111369,24.0000,C148,C,25.800000
890,891,0,3,"Dooley, Mr. Patrick",male,1.300882,0,0,370376,1.7500,NaN,Q,6.665000

**Explanation**

Select the age and fare columns and reassign them to be the age and fare minus my custom array of [1, 6]. This subtracts 1 from each age and 6 from each fare.

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

In [15]:
#1
df['Characters in Name'] = df['Name'].apply(len)
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare (Euros),Characters in Name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638,51
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,21
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,11.180000,21
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,25.800000,27
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,20.167000,39
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.800000,21
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,6.665000,19

**Explanation**

Create a new column using df['Characters in Name']. Use len to count each character (including spaces and punctuation) in each name.

In [16]:
#2
df['Fare - Age'] = df.apply(lambda row: row['Fare'] - row['Age'], axis=1)
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare (Euros),Characters in Name,Fare - Age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000,23,-14.7500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638,51,33.2833
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,21,-18.0750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000,44,18.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000,24,-26.9500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,11.180000,21,-14.0000
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,25.800000,27,11.0000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,20.167000,39,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.800000,21,4.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,6.665000,19,-24.2500

**Explanation**

Create a new column for fares minus ages: df['Fare - Age']. Used the apply() method to perform the function across the dataframe. Axis=1 applies the function across rows. Uses lambda function to grab the Fare and Age in each column and subtract the Age from the Fare.

In [17]:
#3
df = df.round(1)
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare (Euros),Characters in Name,Fare - Age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2,NaN,S,6.2,23,-14.8
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.3,C85,C,61.3,51,33.3
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9,NaN,S,6.8,21,-18.1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S,45.7,44,18.1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0,NaN,S,6.9,24,-27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0,NaN,S,11.2,21,-14.0
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0,B42,S,25.8,27,11.0
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4,NaN,S,20.2,39,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0,C148,C,25.8,21,4.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.8,NaN,Q,6.7,19,-24.2

**Explanation**

use df.round(1) to round numerical values across the entire dataset to one decimal place.

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

In [18]:
#1
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare (Euros),Characters in Name,Fare - Age
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2,NaN,S,6.2,23,-14.8
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.3,C85,C,61.3,51,33.3
2,3,1,3,"Heikkinen, Miss Laina",1,26.0,0,0,STON/O2. 3101282,7.9,NaN,S,6.8,21,-18.1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1,C123,S,45.7,44,18.1
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0,NaN,S,6.9,24,-27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0,NaN,S,11.2,21,-14.0
887,888,1,1,"Graham, Miss Margaret Edith",1,19.0,0,0,112053,30.0,B42,S,25.8,27,11.0
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",1,NaN,1,2,W./C. 6607,23.4,NaN,S,20.2,39,NaN
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0,C148,C,25.8,21,4.0
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.8,NaN,Q,6.7,19,-24.2

**Explanation**

Used mapping to change 'male' entries to a numerical value of 0 and 'female' entries to 1. Reassign these changed values to the 'Sex' column.

In [19]:
#2
categories = df['Age'].map(
    lambda x: 'Child' if pd.notnull(x) and x < 18
    else ('Adult' if pd.notnull(x) and x < 60
          else 'Senior' if pd.notnull(x) else np.nan))

df['Age Group'] = categories
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare (Euros),Characters in Name,Fare - Age,Age Group
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2,NaN,S,6.2,23,-14.8,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.3,C85,C,61.3,51,33.3,Adult
2,3,1,3,"Heikkinen, Miss Laina",1,26.0,0,0,STON/O2. 3101282,7.9,NaN,S,6.8,21,-18.1,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1,C123,S,45.7,44,18.1,Adult
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0,NaN,S,6.9,24,-27.0,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0,NaN,S,11.2,21,-14.0,Adult
887,888,1,1,"Graham, Miss Margaret Edith",1,19.0,0,0,112053,30.0,B42,S,25.8,27,11.0,Adult
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",1,NaN,1,2,W./C. 6607,23.4,NaN,S,20.2,39,NaN,NaN
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0,C148,C,25.8,21,4.0,Adult
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.8,NaN,Q,6.7,19,-24.2,Adult

**Explanation**

Create new variable categories to conditionally create a category for child, adult, and senior based on numerical values. Also conditionally searches for null values and returns rows with null ages to null age groups (using if pd.notnull(x) and else np.nan). Creates a new column called 'Age Group' and assigns it to these new categories.

### Part 8: Part 3 in Plain Python ###
1. Show only the rows where the age is above 60.

In [20]:
import csv
import urllib.request

with urllib.request.urlopen("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv") as response:
    lines = [line.decode("utf-8") for line in response.readlines()]
    reader = csv.DictReader(lines)
    dataList = list(reader)

overSixty = []

for row in dataList:
    age = row["Age"]

    if age != "":
        age = float(age)
        if age > 60:
            overSixty.append(row)

for p in overSixty:
    print(p)

{'PassengerId': '34', 'Survived': '0', 'Pclass': '2', 'Name': 'Wheadon, Mr. Edward H', 'Sex': 'male', 'Age': '66', 'SibSp': '0', 'Parch': '0', 'Ticket': 'C.A. 24579', 'Fare': '10.5', 'Cabin': '', 'Embarked': 'S'}
{'PassengerId': '55', 'Survived': '0', 'Pclass': '1', 'Name': 'Ostby, Mr. Engelhart Cornelius', 'Sex': 'male', 'Age': '65', 'SibSp': '0', 'Parch': '1', 'Ticket': '113509', 'Fare': '61.9792', 'Cabin': 'B30', 'Embarked': 'C'}
{'PassengerId': '97', 'Survived': '0', 'Pclass': '1', 'Name': 'Goldschmidt, Mr. George B', 'Sex': 'male', 'Age': '71', 'SibSp': '0', 'Parch': '0', 'Ticket': 'PC 17754', 'Fare': '34.6542', 'Cabin': 'A5', 'Embarked': 'C'}
{'PassengerId': '117', 'Survived': '0', 'Pclass': '3', 'Name': 'Connors, Mr. Patrick', 'Sex': 'male', 'Age': '70.5', 'SibSp': '0', 'Parch': '0', 'Ticket': '370369', 'Fare': '7.75', 'Cabin': '', 'Embarked': 'Q'}
{'PassengerId': '171', 'Survived': '0', 'Pclass': '1', 'Name': 'Van der hoef, Mr. Wyckoff', 'Sex': 'male', 'Age': '61', 'SibSp': '0', 'Parch': '0', 'Ticket': '111240', 'Fare': '33.5', 'Cabin': 'B19', 'Embarked': 'S'}
{'PassengerId': '253', 'Survived': '0', 'Pclass': '1', 'Name': 'Stead, Mr. William Thomas', 'Sex': 'male', 'Age': '62', 'SibSp': '0', 'Parch': '0', 'Ticket': '113514', 'Fare': '26.55', 'Cabin': 'C87', 'Embarked': 'S'}
{'PassengerId': '276', 'Survived': '1', 'Pclass': '1', 'Name': 'Andrews, Miss Kornelia Theodosia', 'Sex': 'female', 'Age': '63', 'SibSp': '1', 'Parch': '0', 'Ticket': '13502', 'Fare': '77.9583', 'Cabin': 'D7', 'Embarked': 'S'}
{'PassengerId': '281', 'Survived': '0', 'Pclass': '3', 'Name': 'Duane, Mr. Frank', 'Sex': 'male', 'Age': '65', 'SibSp': '0', 'Parch': '0', 'Ticket': '336439', 'Fare': '7.75', 'Cabin': '', 'Embarked': 'Q'}
{'PassengerId': '327', 'Survived': '0', 'Pclass': '3', 'Name': 'Nysveen, Mr. Johan Hansen', 'Sex': 'male', 'Age': '61', 'SibSp': '0', 'Parch': '0', 'Ticket': '345364', 'Fare': '6.2375', 'Cabin': '', 'Embarked': 'S'}
{'PassengerId': '439', 'Survived': '0', 'Pclass': '1', 'Name': 'Fortune, Mr. Mark', 'Sex': 'male', 'Age': '64', 'SibSp': '1', 'Parch': '4', 'Ticket': '19950', 'Fare': '263', 'Cabin': 'C23 C25 C27', 'Embarked': 'S'}
{'PassengerId': '457', 'Survived': '0', 'Pclass': '1', 'Name': 'Millet, Mr. Francis Davis', 'Sex': 'male', 'Age': '65', 'SibSp': '0', 'Parch': '0', 'Ticket': '13509', 'Fare': '26.55', 'Cabin': 'E38', 'Embarked': 'S'}
{'PassengerId': '484', 'Survived': '1', 'Pclass': '3', 'Name': 'Turkula, Mrs. (Hedwig)', 'Sex': 'female', 'Age': '63', 'SibSp': '0', 'Parch': '0', 'Ticket': '4134', 'Fare': '9.5875', 'Cabin': '', 'Embarked': 'S'}
{'PassengerId': '494', 'Survived': '0', 'Pclass': '1', 'Name': 'Artagaveytia, Mr. Ramon', 'Sex': 'male', 'Age': '71', 'SibSp': '0', 'Parch': '0', 'Ticket': 'PC 17609', 'Fare': '49.5042', 'Cabin': '', 'Embarked': 'C'}
{'PassengerId': '546', 'Survived': '0', 'Pclass': '1', 'Name': 'Nicholson, Mr. Arthur Ernest', 'Sex': 'male', 'Age': '64', 'SibSp': '0', 'Parch': '0', 'Ticket': '693', 'Fare': '26', 'Cabin': '', 'Embarked': 'S'}
{'PassengerId': '556', 'Survived': '0', 'Pclass': '1', 'Name': 'Wright, Mr. George', 'Sex': 'male', 'Age': '62', 'SibSp': '0', 'Parch': '0', 'Ticket': '113807', 'Fare': '26.55', 'Cabin': '', 'Embarked': 'S'}
{'PassengerId': '571', 'Survived': '1', 'Pclass': '2', 'Name': 'Harris, Mr. George', 'Sex': 'male', 'Age': '62', 'SibSp': '0', 'Parch': '0', 'Ticket': 'S.W./PP 752', 'Fare': '10.5', 'Cabin': '', 'Embarked': 'S'}
{'PassengerId': '626', 'Survived': '0', 'Pclass': '1', 'Name': 'Sutton, Mr. Frederick', 'Sex': 'male', 'Age': '61', 'SibSp': '0', 'Parch': '0', 'Ticket': '36963', 'Fare': '32.3208', 'Cabin': 'D50', 'Embarked': 'S'}
{'PassengerId': '631', 'Survived': '1', 'Pclass': '1', 'Name': 'Barkworth, Mr. Algernon Henry Wilson', 'Sex': 'male', 'Age': '80', 'SibSp': '0', 'Parch': '0', 'Ticket': '27042', 'Fare': '30', 'Cabin': 'A23', 'Embarked': 'S'}
{'PassengerId': '673', 'Survived': '0', 'Pclass': '2', 'Name': 'Mitchell, Mr. Henry Michael', 'Sex': 'male', 'Age': '70', 'SibSp': '0', 'Parch': '0', 'Ticket': 'C.A. 24580', 'Fare': '10.5', 'Cabin': '', 'Embarked': 'S'}
{'PassengerId': '746', 'Survived': '0', 'Pclass': '1', 'Name': 'Crosby, Capt. Edward Gifford', 'Sex': 'male', 'Age': '70', 'SibSp': '1', 'Parch': '1', 'Ticket': 'WE/P 5735', 'Fare': '71', 'Cabin': 'B22', 'Embarked': 'S'}
{'PassengerId': '830', 'Survived': '1', 'Pclass': '1', 'Name': 'Stone, Mrs. George Nelson (Martha Evelyn)', 'Sex': 'female', 'Age': '62', 'SibSp': '0', 'Parch': '0', 'Ticket': '113572', 'Fare': '80', 'Cabin': 'B28', 'Embarked': ''}
{'PassengerId': '852', 'Survived': '0', 'Pclass': '3', 'Name': 'Svensson, Mr. Johan', 'Sex': 'male', 'Age': '74', 'SibSp': '0', 'Parch': '0', 'Ticket': '347060', 'Fare': '7.775', 'Cabin': '', 'Embarked': 'S'}

**Explanation**

I used csv and which is a built-in Python module and urllib to read the url. These are both part of Python's standard library and are not external. I first used urllib to open the url and csv to read the csv. Then, I converted the csv into a list of dictionaries.

I created an empty list for the rows of passengers above 60. Using a for loop I visit each row's 'Age' column, check if it is empty, convert it to a float, and then add the row to the empty list if the age is over 60. Then I print each row.

### Part 8: Part 2 in Plain Python ###
3. Select a single row from the dataset.

In [21]:
import csv
import urllib.request

with urllib.request.urlopen("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv") as response:
    lines = [line.decode("utf-8") for line in response.readlines()]
    reader = csv.DictReader(lines)
    dataList = list(reader)

print(dataList[66])

{'PassengerId': '67', 'Survived': '1', 'Pclass': '2', 'Name': 'Nye, Mrs. (Elizabeth Ramell)', 'Sex': 'female', 'Age': '29', 'SibSp': '0', 'Parch': '0', 'Ticket': 'C.A. 29395', 'Fare': '10.5', 'Cabin': 'F33', 'Embarked': 'S'}

**Explanation**

Again, I used csv and urllib to read the url and csv, then convert it into a list of dictionaries. Then, I printed the 66th element within the list.

### Part 8: Part 5 in Plain Python ###
1. Create a new column that converts fares from USD to Euros.

In [22]:
import csv
import urllib.request

with urllib.request.urlopen("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv") as response:
    lines = [line.decode("utf-8") for line in response.readlines()]
    reader = csv.DictReader(lines)
    dataList = list(reader)

for row in dataList:
    fare = row["Fare"]

    if fare != "":
        fare_usd = float(fare)
        fare_eur = fare_usd * 0.86
        row["Fare (Euros)"] = round(fare_eur, 2)
    else:
        row["Fare (Euros)"] = ""

for row in dataList:
    print(row)

{'PassengerId': '1', 'Survived': '0', 'Pclass': '3', 'Name': 'Braund, Mr. Owen Harris', 'Sex': 'male', 'Age': '22', 'SibSp': '1', 'Parch': '0', 'Ticket': 'A/5 21171', 'Fare': '7.25', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.24}
{'PassengerId': '2', 'Survived': '1', 'Pclass': '1', 'Name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Sex': 'female', 'Age': '38', 'SibSp': '1', 'Parch': '0', 'Ticket': 'PC 17599', 'Fare': '71.2833', 'Cabin': 'C85', 'Embarked': 'C', 'Fare (Euros)': 61.3}
{'PassengerId': '3', 'Survived': '1', 'Pclass': '3', 'Name': 'Heikkinen, Miss Laina', 'Sex': 'female', 'Age': '26', 'SibSp': '0', 'Parch': '0', 'Ticket': 'STON/O2. 3101282', 'Fare': '7.925', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.82}
{'PassengerId': '4', 'Survived': '1', 'Pclass': '1', 'Name': 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Sex': 'female', 'Age': '35', 'SibSp': '1', 'Parch': '0', 'Ticket': '113803', 'Fare': '53.1', 'Cabin': 'C123', 'Embarked': 'S', 'Fare (Euros)': 45.67}
{'PassengerId': '5', 'Survived': '0', 'Pclass': '3', 'Name': 'Allen, Mr. William Henry', 'Sex': 'male', 'Age': '35', 'SibSp': '0', 'Parch': '0', 'Ticket': '373450', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.92}
{'PassengerId': '6', 'Survived': '0', 'Pclass': '3', 'Name': 'Moran, Mr. James', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '330877', 'Fare': '8.4583', 'Cabin': '', 'Embarked': 'Q', 'Fare (Euros)': 7.27}
{'PassengerId': '7', 'Survived': '0', 'Pclass': '1', 'Name': 'McCarthy, Mr. Timothy J', 'Sex': 'male', 'Age': '54', 'SibSp': '0', 'Parch': '0', 'Ticket': '17463', 'Fare': '51.8625', 'Cabin': 'E46', 'Embarked': 'S', 'Fare (Euros)': 44.6}
{'PassengerId': '8', 'Survived': '0', 'Pclass': '3', 'Name': 'Palsson, Master Gosta Leonard', 'Sex': 'male', 'Age': '2', 'SibSp': '3', 'Parch': '1', 'Ticket': '349909', 'Fare': '21.075', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 18.12}
{'PassengerId': '9', 'Survived': '1', 'Pclass': '3', 'Name': 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'Sex': 'female', 'Age': '27', 'SibSp': '0', 'Parch': '2', 'Ticket': '347742', 'Fare': '11.1333', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 9.57}
{'PassengerId': '10', 'Survived': '1', 'Pclass': '2', 'Name': 'Nasser, Mrs. Nicholas (Adele Achem)', 'Sex': 'female', 'Age': '14', 'SibSp': '1', 'Parch': '0', 'Ticket': '237736', 'Fare': '30.0708', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 25.86}
{'PassengerId': '11', 'Survived': '1', 'Pclass': '3', 'Name': 'Sandstrom, Miss Marguerite Rut', 'Sex': 'female', 'Age': '4', 'SibSp': '1', 'Parch': '1', 'Ticket': 'PP 9549', 'Fare': '16.7', 'Cabin': 'G6', 'Embarked': 'S', 'Fare (Euros)': 14.36}
{'PassengerId': '12', 'Survived': '1', 'Pclass': '1', 'Name': 'Bonnell, Miss Elizabeth', 'Sex': 'female', 'Age': '58', 'SibSp': '0', 'Parch': '0', 'Ticket': '113783', 'Fare': '26.55', 'Cabin': 'C103', 'Embarked': 'S', 'Fare (Euros)': 22.83}
{'PassengerId': '13', 'Survived': '0', 'Pclass': '3', 'Name': 'Saundercock, Mr. William Henry', 'Sex': 'male', 'Age': '20', 'SibSp': '0', 'Parch': '0', 'Ticket': 'A/5. 2151', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.92}
{'PassengerId': '14', 'Survived': '0', 'Pclass': '3', 'Name': 'Andersson, Mr. Anders Johan', 'Sex': 'male', 'Age': '39', 'SibSp': '1', 'Parch': '5', 'Ticket': '347082', 'Fare': '31.275', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 26.9}
{'PassengerId': '15', 'Survived': '0', 'Pclass': '3', 'Name': 'Vestrom, Miss Hulda Amanda Adolfina', 'Sex': 'female', 'Age': '14', 'SibSp': '0', 'Parch': '0', 'Ticket': '350406', 'Fare': '7.8542', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.75}
{'PassengerId': '16', 'Survived': '1', 'Pclass': '2', 'Name': 'Hewlett, Mrs. (Mary D Kingcome) ', 'Sex': 'female', 'Age': '55', 'SibSp': '0', 'Parch': '0', 'Ticket': '248706', 'Fare': '16', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 13.76}
{'PassengerId': '17', 'Survived': '0', 'Pclass': '3', 'Name': 'Rice, Master Eugene', 'Sex': 'male', 'Age': '2', 'SibSp': '4', 'Parch': '1', 'Ticket': '382652', 'Fare': '29.125', 'Cabin': '', 'Embarked': 'Q', 'Fare (Euros)': 25.05}
{'PassengerId': '18', 'Survived': '1', 'Pclass': '2', 'Name': 'Williams, Mr. Charles Eugene', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '244373', 'Fare': '13', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 11.18}
{'PassengerId': '19', 'Survived': '0', 'Pclass': '3', 'Name': 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 'Sex': 'female', 'Age': '31', 'SibSp': '1', 'Parch': '0', 'Ticket': '345763', 'Fare': '18', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 15.48}
{'PassengerId': '20', 'Survived': '1', 'Pclass': '3', 'Name': 'Masselmani, Mrs. Fatima', 'Sex': 'female', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '2649', 'Fare': '7.225', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 6.21}
{'PassengerId': '21', 'Survived': '0', 'Pclass': '2', 'Name': 'Fynney, Mr. Joseph J', 'Sex': 'male', 'Age': '35', 'SibSp': '0', 'Parch': '0', 'Ticket': '239865', 'Fare': '26', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 22.36}
{'PassengerId': '22', 'Survived': '1', 'Pclass': '2', 'Name': 'Beesley, Mr. Lawrence', 'Sex': 'male', 'Age': '34', 'SibSp': '0', 'Parch': '0', 'Ticket': '248698', 'Fare': '13', 'Cabin': 'D56', 'Embarked': 'S', 'Fare (Euros)': 11.18}
{'PassengerId': '23', 'Survived': '1', 'Pclass': '3', 'Name': 'McGowan, Miss Anna "Annie"', 'Sex': 'female', 'Age': '15', 'SibSp': '0', 'Parch': '0', 'Ticket': '330923', 'Fare': '8.0292', 'Cabin': '', 'Embarked': 'Q', 'Fare (Euros)': 6.91}
{'PassengerId': '24', 'Survived': '1', 'Pclass': '1', 'Name': 'Sloper, Mr. William Thompson', 'Sex': 'male', 'Age': '28', 'SibSp': '0', 'Parch': '0', 'Ticket': '113788', 'Fare': '35.5', 'Cabin': 'A6', 'Embarked': 'S', 'Fare (Euros)': 30.53}
{'PassengerId': '25', 'Survived': '0', 'Pclass': '3', 'Name': 'Palsson, Miss Torborg Danira', 'Sex': 'female', 'Age': '8', 'SibSp': '3', 'Parch': '1', 'Ticket': '349909', 'Fare': '21.075', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 18.12}
{'PassengerId': '26', 'Survived': '1', 'Pclass': '3', 'Name': 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'Sex': 'female', 'Age': '38', 'SibSp': '1', 'Parch': '5', 'Ticket': '347077', 'Fare': '31.3875', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 26.99}
{'PassengerId': '27', 'Survived': '0', 'Pclass': '3', 'Name': 'Emir, Mr. Farred Chehab', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '2631', 'Fare': '7.225', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 6.21}
{'PassengerId': '28', 'Survived': '0', 'Pclass': '1', 'Name': 'Fortune, Mr. Charles Alexander', 'Sex': 'male', 'Age': '19', 'SibSp': '3', 'Parch': '2', 'Ticket': '19950', 'Fare': '263', 'Cabin': 'C23 C25 C27', 'Embarked': 'S', 'Fare (Euros)': 226.18}
{'PassengerId': '29', 'Survived': '1', 'Pclass': '3', 'Name': 'O\'Dwyer, Miss Ellen "Nellie"', 'Sex': 'female', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '330959', 'Fare': '7.8792', 'Cabin': '', 'Embarked': 'Q', 'Fare (Euros)': 6.78}
{'PassengerId': '30', 'Survived': '0', 'Pclass': '3', 'Name': 'Todoroff, Mr. Lalio', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '349216', 'Fare': '7.8958', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.79}
{'PassengerId': '31', 'Survived': '0', 'Pclass': '1', 'Name': 'Uruchurtu, Don. Manuel E', 'Sex': 'male', 'Age': '40', 'SibSp': '0', 'Parch': '0', 'Ticket': 'PC 17601', 'Fare': '27.7208', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 23.84}
{'PassengerId': '32', 'Survived': '1', 'Pclass': '1', 'Name': 'Spencer, Mrs. William Augustus (Marie Eugenie)', 'Sex': 'female', 'Age': '', 'SibSp': '1', 'Parch': '0', 'Ticket': 'PC 17569', 'Fare': '146.5208', 'Cabin': 'B78', 'Embarked': 'C', 'Fare (Euros)': 126.01}
{'PassengerId': '33', 'Survived': '1', 'Pclass': '3', 'Name': 'Glynn, Miss Mary Agatha', 'Sex': 'female', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '335677', 'Fare': '7.75', 'Cabin': '', 'Embarked': 'Q', 'Fare (Euros)': 6.67}
{'PassengerId': '34', 'Survived': '0', 'Pclass': '2', 'Name': 'Wheadon, Mr. Edward H', 'Sex': 'male', 'Age': '66', 'SibSp': '0', 'Parch': '0', 'Ticket': 'C.A. 24579', 'Fare': '10.5', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 9.03}
{'PassengerId': '35', 'Survived': '0', 'Pclass': '1', 'Name': 'Meyer, Mr. Edgar Joseph', 'Sex': 'male', 'Age': '28', 'SibSp': '1', 'Parch': '0', 'Ticket': 'PC 17604', 'Fare': '82.1708', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 70.67}
{'PassengerId': '36', 'Survived': '0', 'Pclass': '1', 'Name': 'Holverson, Mr. Alexander Oskar', 'Sex': 'male', 'Age': '42', 'SibSp': '1', 'Parch': '0', 'Ticket': '113789', 'Fare': '52', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 44.72}
{'PassengerId': '37', 'Survived': '1', 'Pclass': '3', 'Name': 'Mamee, Mr. Hanna', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '2677', 'Fare': '7.2292', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 6.22}
{'PassengerId': '38', 'Survived': '0', 'Pclass': '3', 'Name': 'Cann, Mr. Ernest Charles', 'Sex': 'male', 'Age': '21', 'SibSp': '0', 'Parch': '0', 'Ticket': 'A./5. 2152', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.92}
{'PassengerId': '39', 'Survived': '0', 'Pclass': '3', 'Name': 'Vander Planke, Miss Augusta Maria', 'Sex': 'female', 'Age': '18', 'SibSp': '2', 'Parch': '0', 'Ticket': '345764', 'Fare': '18', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 15.48}
{'PassengerId': '40', 'Survived': '1', 'Pclass': '3', 'Name': 'Nicola-Yarred, Miss Jamila', 'Sex': 'female', 'Age': '14', 'SibSp': '1', 'Parch': '0', 'Ticket': '2651', 'Fare': '11.2417', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 9.67}
{'PassengerId': '41', 'Survived': '0', 'Pclass': '3', 'Name': 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'Sex': 'female', 'Age': '40', 'SibSp': '1', 'Parch': '0', 'Ticket': '7546', 'Fare': '9.475', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 8.15}
{'PassengerId': '42', 'Survived': '0', 'Pclass': '2', 'Name': 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 'Sex': 'female', 'Age': '27', 'SibSp': '1', 'Parch': '0', 'Ticket': '11668', 'Fare': '21', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 18.06}
{'PassengerId': '43', 'Survived': '0', 'Pclass': '3', 'Name': 'Kraeff, Mr. Theodor', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '349253', 'Fare': '7.8958', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 6.79}
{'PassengerId': '44', 'Survived': '1', 'Pclass': '2', 'Name': 'Laroche, Miss Simonne Marie Anne Andree', 'Sex': 'female', 'Age': '3', 'SibSp': '1', 'Parch': '2', 'Ticket': 'SC/Paris 2123', 'Fare': '41.5792', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 35.76}
{'PassengerId': '45', 'Survived': '1', 'Pclass': '3', 'Name': 'Devaney, Miss Margaret Delia', 'Sex': 'female', 'Age': '19', 'SibSp': '0', 'Parch': '0', 'Ticket': '330958', 'Fare': '7.8792', 'Cabin': '', 'Embarked': 'Q', 'Fare (Euros)': 6.78}
{'PassengerId': '46', 'Survived': '0', 'Pclass': '3', 'Name': 'Rogers, Mr. William John', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': 'S.C./A.4. 23567', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.92}
{'PassengerId': '47', 'Survived': '0', 'Pclass': '3', 'Name': 'Lennon, Mr. Denis', 'Sex': 'male', 'Age': '', 'SibSp': '1', 'Parch': '0', 'Ticket': '370371', 'Fare': '15.5', 'Cabin': '', 'Embarked': 'Q', 'Fare (Euros)': 13.33}
{'PassengerId': '48', 'Survived': '1', 'Pclass': '3', 'Name': "O'Driscoll, Miss Bridget", 'Sex': 'female', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '14311', 'Fare': '7.75', 'Cabin': '', 'Embarked': 'Q', 'Fare (Euros)': 6.67}
{'PassengerId': '49', 'Survived': '0', 'Pclass': '3', 'Name': 'Samaan, Mr. Youssef', 'Sex': 'male', 'Age': '', 'SibSp': '2', 'Parch': '0', 'Ticket': '2662', 'Fare': '21.6792', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 18.64}
{'PassengerId': '50', 'Survived': '0', 'Pclass': '3', 'Name': 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 'Sex': 'female', 'Age': '18', 'SibSp': '1', 'Parch': '0', 'Ticket': '349237', 'Fare': '17.8', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 15.31}
{'PassengerId': '51', 'Survived': '0', 'Pclass': '3', 'Name': 'Panula, Master Juha Niilo', 'Sex': 'male', 'Age': '7', 'SibSp': '4', 'Parch': '1', 'Ticket': '3101295', 'Fare': '39.6875', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 34.13}
{'PassengerId': '52', 'Survived': '0', 'Pclass': '3', 'Name': 'Nosworthy, Mr. Richard Cater', 'Sex': 'male', 'Age': '21', 'SibSp': '0', 'Parch': '0', 'Ticket': 'A/4. 39886', 'Fare': '7.8', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.71}
{'PassengerId': '53', 'Survived': '1', 'Pclass': '1', 'Name': 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'Sex': 'female', 'Age': '49', 'SibSp': '1', 'Parch': '0', 'Ticket': 'PC 17572', 'Fare': '76.7292', 'Cabin': 'D33', 'Embarked': 'C', 'Fare (Euros)': 65.99}
{'PassengerId': '54', 'Survived': '1', 'Pclass': '2', 'Name': 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'Sex': 'female', 'Age': '29', 'SibSp': '1', 'Parch': '0', 'Ticket': '2926', 'Fare': '26', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 22.36}
{'PassengerId': '55', 'Survived': '0', 'Pclass': '1', 'Name': 'Ostby, Mr. Engelhart Cornelius', 'Sex': 'male', 'Age': '65', 'SibSp': '0', 'Parch': '1', 'Ticket': '113509', 'Fare': '61.9792', 'Cabin': 'B30', 'Embarked': 'C', 'Fare (Euros)': 53.3}
{'PassengerId': '56', 'Survived': '1', 'Pclass': '1', 'Name': 'Woolner, Mr. Hugh', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '19947', 'Fare': '35.5', 'Cabin': 'C52', 'Embarked': 'S', 'Fare (Euros)': 30.53}
{'PassengerId': '57', 'Survived': '1', 'Pclass': '2', 'Name': 'Rugg, Miss Emily', 'Sex': 'female', 'Age': '21', 'SibSp': '0', 'Parch': '0', 'Ticket': 'C.A. 31026', 'Fare': '10.5', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 9.03}
{'PassengerId': '58', 'Survived': '0', 'Pclass': '3', 'Name': 'Novel, Mr. Mansouer', 'Sex': 'male', 'Age': '28.5', 'SibSp': '0', 'Parch': '0', 'Ticket': '2697', 'Fare': '7.2292', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 6.22}
{'PassengerId': '59', 'Survived': '1', 'Pclass': '2', 'Name': 'West, Miss Constance Mirium', 'Sex': 'female', 'Age': '5', 'SibSp': '1', 'Parch': '2', 'Ticket': 'C.A. 34651', 'Fare': '27.75', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 23.86}
{'PassengerId': '60', 'Survived': '0', 'Pclass': '3', 'Name': 'Goodwin, Master William Frederick', 'Sex': 'male', 'Age': '11', 'SibSp': '5', 'Parch': '2', 'Ticket': 'CA 2144', 'Fare': '46.9', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 40.33}
{'PassengerId': '61', 'Survived': '0', 'Pclass': '3', 'Name': 'Sirayanian, Mr. Orsen', 'Sex': 'male', 'Age': '22', 'SibSp': '0', 'Parch': '0', 'Ticket': '2669', 'Fare': '7.2292', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 6.22}
{'PassengerId': '62', 'Survived': '1', 'Pclass': '1', 'Name': 'Icard, Miss Amelie', 'Sex': 'female', 'Age': '38', 'SibSp': '0', 'Parch': '0', 'Ticket': '113572', 'Fare': '80', 'Cabin': 'B28', 'Embarked': '', 'Fare (Euros)': 68.8}
{'PassengerId': '63', 'Survived': '0', 'Pclass': '1', 'Name': 'Harris, Mr. Henry Birkhardt', 'Sex': 'male', 'Age': '45', 'SibSp': '1', 'Parch': '0', 'Ticket': '36973', 'Fare': '83.475', 'Cabin': 'C83', 'Embarked': 'S', 'Fare (Euros)': 71.79}
{'PassengerId': '64', 'Survived': '0', 'Pclass': '3', 'Name': 'Skoog, Master Harald', 'Sex': 'male', 'Age': '4', 'SibSp': '3', 'Parch': '2', 'Ticket': '347088', 'Fare': '27.9', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 23.99}
{'PassengerId': '65', 'Survived': '0', 'Pclass': '1', 'Name': 'Stewart, Mr. Albert A', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': 'PC 17605', 'Fare': '27.7208', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 23.84}
{'PassengerId': '66', 'Survived': '1', 'Pclass': '3', 'Name': 'Moubarek, Master Gerios', 'Sex': 'male', 'Age': '', 'SibSp': '1', 'Parch': '1', 'Ticket': '2661', 'Fare': '15.2458', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 13.11}
{'PassengerId': '67', 'Survived': '1', 'Pclass': '2', 'Name': 'Nye, Mrs. (Elizabeth Ramell)', 'Sex': 'female', 'Age': '29', 'SibSp': '0', 'Parch': '0', 'Ticket': 'C.A. 29395', 'Fare': '10.5', 'Cabin': 'F33', 'Embarked': 'S', 'Fare (Euros)': 9.03}
{'PassengerId': '68', 'Survived': '0', 'Pclass': '3', 'Name': 'Crease, Mr. Ernest James', 'Sex': 'male', 'Age': '19', 'SibSp': '0', 'Parch': '0', 'Ticket': 'S.P. 3464', 'Fare': '8.1583', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 7.02}
{'PassengerId': '69', 'Survived': '1', 'Pclass': '3', 'Name': 'Andersson, Miss Erna Alexandra', 'Sex': 'female', 'Age': '17', 'SibSp': '4', 'Parch': '2', 'Ticket': '3101281', 'Fare': '7.925', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.82}
{'PassengerId': '70', 'Survived': '0', 'Pclass': '3', 'Name': 'Kink, Mr. Vincenz', 'Sex': 'male', 'Age': '26', 'SibSp': '2', 'Parch': '0', 'Ticket': '315151', 'Fare': '8.6625', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 7.45}
{'PassengerId': '71', 'Survived': '0', 'Pclass': '2', 'Name': 'Jenkin, Mr. Stephen Curnow', 'Sex': 'male', 'Age': '32', 'SibSp': '0', 'Parch': '0', 'Ticket': 'C.A. 33111', 'Fare': '10.5', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 9.03}
{'PassengerId': '72', 'Survived': '0', 'Pclass': '3', 'Name': 'Goodwin, Miss Lillian Amy', 'Sex': 'female', 'Age': '16', 'SibSp': '5', 'Parch': '2', 'Ticket': 'CA 2144', 'Fare': '46.9', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 40.33}
{'PassengerId': '73', 'Survived': '0', 'Pclass': '2', 'Name': 'Hood, Mr. Ambrose Jr', 'Sex': 'male', 'Age': '21', 'SibSp': '0', 'Parch': '0', 'Ticket': 'S.O.C. 14879', 'Fare': '73.5', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 63.21}
{'PassengerId': '74', 'Survived': '0', 'Pclass': '3', 'Name': 'Chronopoulos, Mr. Apostolos', 'Sex': 'male', 'Age': '26', 'SibSp': '1', 'Parch': '0', 'Ticket': '2680', 'Fare': '14.4542', 'Cabin': '', 'Embarked': 'C', 'Fare (Euros)': 12.43}
{'PassengerId': '75', 'Survived': '1', 'Pclass': '3', 'Name': 'Bing, Mr. Lee', 'Sex': 'male', 'Age': '32', 'SibSp': '0', 'Parch': '0', 'Ticket': '1601', 'Fare': '56.4958', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 48.59}
{'PassengerId': '76', 'Survived': '0', 'Pclass': '3', 'Name': 'Moen, Mr. Sigurd Hansen', 'Sex': 'male', 'Age': '25', 'SibSp': '0', 'Parch': '0', 'Ticket': '348123', 'Fare': '7.65', 'Cabin': 'F G73', 'Embarked': 'S', 'Fare (Euros)': 6.58}
{'PassengerId': '77', 'Survived': '0', 'Pclass': '3', 'Name': 'Staneff, Mr. Ivan', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '349208', 'Fare': '7.8958', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.79}
{'PassengerId': '78', 'Survived': '0', 'Pclass': '3', 'Name': 'Moutal, Mr. Rahamin Haim', 'Sex': 'male', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '374746', 'Fare': '8.05', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 6.92}
{'PassengerId': '79', 'Survived': '1', 'Pclass': '2', 'Name': 'Caldwell, Master Alden Gates', 'Sex': 'male', 'Age': '0.83', 'SibSp': '0', 'Parch': '2', 'Ticket': '248738', 'Fare': '29', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 24.94}
{'PassengerId': '80', 'Survived': '1', 'Pclass': '3', 'Name': 'Dowdell, Miss Elizabeth', 'Sex': 'female', 'Age': '30', 'SibSp': '0', 'Parch': '0', 'Ticket': '364516', 'Fare': '12.475', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 10.73}
{'PassengerId': '81', 'Survived': '0', 'Pclass': '3', 'Name': 'Waelens, Mr. Achille', 'Sex': 'male', 'Age': '22', 'SibSp': '0', 'Parch': '0', 'Ticket': '345767', 'Fare': '9', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 7.74}
{'PassengerId': '82', 'Survived': '1', 'Pclass': '3', 'Name': 'Sheerlinck, Mr. Jan Baptist', 'Sex': 'male', 'Age': '29', 'SibSp': '0', 'Parch': '0', 'Ticket': '345779', 'Fare': '9.5', 'Cabin': '', 'Embarked': 'S', 'Fare (Euros)': 8.17}
{'PassengerId': '83', 'Survived': '1', 'Pclass': '3', 'Name': 'McDermott, Miss Brigdet Delia', 'Sex': 'female', 'Age': '', 'SibSp': '0', 'Parch': '0', 'Ticket': '330932', 'Fare': '7.7875', 'Cabin': '', 'Embarked': 'Q', 'Fare (Euros)': 6.7}

**Explanation**

Used csv and urllib to open and read the url and csv, turning it into a list of dictionaries. For each row, the 'Fare' column is selected. If it is not null, the fare will be multiplied by the exchange rate and rounded to 2 decimal places. It gets added to "Fare (Euros)". If the value is null, a null value gets returned for Euros.

**Comparison**

While all cells say they took 0s to run in Google Colab, I noticed that there is slightly faster performance when using Pandas and Numpy than when using plain Python for all three tasks.