# Pandas #

Pandas is a powerful Python library for handling and analyzing data in table format. It makes it easy to manipulate structured data—especially for data science tasks.

## Create a Sample DataFrame ##

In [4]:
# First importing the pandas and numpy libraires
import pandas as pd
import numpy as np

In [5]:
# Creating two list for car makes and months

# a numpy array
products = np.array(['Corolla', 'Camry', 'RAV4', 'Highlander', 'Prius', 'Tacoma'])

# a normal array
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

In [6]:
# Sample monthly sales data (in $1000s)
sales_data = np.array([
    [23, 25, 22, 20, 30, 28, 26, 27, 29, 33, 31, 35],
    [15, 18, 16, 20, 22, 21, 19, 17, 18, 22, 24, 26],
    [35, 33, 30, 28, 36, 34, 32, 38, 37, 39, 40, 42],
    [12, 15, 14, 13, 16, 18, 17, 14, 15, 16, 18, 19],
    [28, 30, 32, 29, 31, 33, 35, 34, 36, 38, 37, 40],
    [20, 22, 21, 19, 23, 25, 24, 22, 23, 25, 26, 27]
])

In [7]:
# Create the DataFrame and print the first five data rows
df = pd.DataFrame(sales_data, index=products, columns=months)
print(df.head())

            Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
Corolla      23   25   22   20   30   28   26   27   29   33   31   35
Camry        15   18   16   20   22   21   19   17   18   22   24   26
RAV4         35   33   30   28   36   34   32   38   37   39   40   42
Highlander   12   15   14   13   16   18   17   14   15   16   18   19
Prius        28   30   32   29   31   33   35   34   36   38   37   40

### Selecting a Column ###
You can select a single column using bracket notation ([]):

**Note**: When you select a single column like this, Pandas returns a **Series**.
A Series is like a single column of a table. It's a **one-dimensional labeled array** that holds data and an associated index.

In [10]:
# Sales in January (returns a Series)
df['Jan']

Corolla       23
Camry         15
RAV4          35
Highlander    12
Prius         28
Tacoma        20
Name: Jan, dtype: int32

- The values are the January sales numbers.

- The index is the list of car models.

- The name of the Series is "Jan".

If you want to keep your result in dataFrame format, you can select it like this instead:

In [13]:
df[['Jan']]

            Jan
Corolla      23
Camry        15
RAV4         35
Highlander   12
Prius        28
Tacoma       20

This returns a DataFrame with just one column instead of a Series. Or you can call the **to_frame()** method.

In [15]:
df['Jan'].to_frame()

            Jan
Corolla      23
Camry        15
RAV4         35
Highlander   12
Prius        28
Tacoma       20

### Selecting Rows by Label (.loc[]) ###
The .loc[] method is used to select rows (and optionally columns) by their labels:

In [17]:
# Get all monthly sales for Camry (returns a series)
df.loc['Camry']

Jan    15
Feb    18
Mar    16
Apr    20
May    22
Jun    21
Jul    19
Aug    17
Sep    18
Oct    22
Nov    24
Dec    26
Name: Camry, dtype: int32

### Selecting a Specific Row and Column ###
You can use df.loc[row_label, column_label] to access a single value in the DataFrame. This is similar to accessing a specific cell in a spreadsheet.

In [19]:
# Get Camry's sales in March
df.loc['Camry', 'Mar']

16

Note:The output is not a Series or DataFrame—it’s just a single value (scalar), such as int or float.

### Selecting Multiple Rows and Columns ###
If you want to return a small sub-table (i.e., a DataFrame), you can use a list of labels:

In [22]:
# Sales of Camry and Prius in Jan and Feb
df.loc[['Camry', 'Prius'], ['Jan', 'Feb']]

       Jan  Feb
Camry   15   18
Prius   28   30

This returns a DataFrame, not a Series

### Selecting Rows by Position (.iloc[]) ###
The .iloc[] method is used to select rows/columns by index position (like in NumPy):

In [25]:
# First row (Corolla)
df.iloc[0].to_frame()

     Corolla
Jan       23
Feb       25
Mar       22
Apr       20
May       30
Jun       28
Jul       26
Aug       27
Sep       29
Oct       33
Nov       31
Dec       35

In [26]:
# Third row, fifth column (RAV4’s May sales)
df.iloc[2, 4]

36

### Selecting a Range or Subsection (Slicing) ###
Slicing in Pandas allows you to extract a portion of the DataFrame—just like slicing lists or arrays in Python—but with labeled data.

You can select a range of rows using .loc[], where you specify the **start and end row labels** by using **":"**.

In [28]:
# Sales from Corolla to RAV4 (inclusive)
df.loc['Corolla':'RAV4']

         Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
Corolla   23   25   22   20   30   28   26   27   29   33   31   35
Camry     15   18   16   20   22   21   19   17   18   22   24   26
RAV4      35   33   30   28   36   34   32   38   37   39   40   42

In [29]:
# Sales in Jan to Mar for all models
df.loc[:, 'Jan':'Mar']

            Jan  Feb  Mar
Corolla      23   25   22
Camry        15   18   16
RAV4         35   33   30
Highlander   12   15   14
Prius        28   30   32
Tacoma       20   22   21

### Boolean Indexing (Conditional Selection) ###
Boolean indexing allows you to filter rows (or columns) of a DataFrame based on a condition. It returns only **the rows for which the condition is True**.

In [31]:
#df['Jan'] > 25 returns a Boolean Series (True/False for each row).
#df[...] uses that Boolean Series to return only rows where the condition is True.
# the resulting dataframe is assigned to "tdf"
tdf = df[df['Jan'] > 25]
print(tdf)

       Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
RAV4    35   33   30   28   36   34   32   38   37   39   40   42
Prius   28   30   32   29   31   33   35   34   36   38   37   40

### Chaining Multiple Conditions ###
- Use & for AND

- Use | for OR

- Each condition must be wrapped in parentheses

- Do not use and/or (those are for single booleans, not Series)

In [33]:
# Models with January > 25 AND February > 30
tdf = df[(df['Jan']>25) & (df['Feb'] > 30)]
print(tdf)

      Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
RAV4   35   33   30   28   36   34   32   38   37   39   40   42

In [34]:
#  Models where March < 20 OR December > 40
tdf = df[(df['Mar']<20) | (df['Dec']>40)]
print(tdf)

            Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
Camry        15   18   16   20   22   21   19   17   18   22   24   26
RAV4         35   33   30   28   36   34   32   38   37   39   40   42
Highlander   12   15   14   13   16   18   17   14   15   16   18   19

### Reindexing ###
Reindexing means changing the order of existing row or column labels or introducing new ones. This is especially useful when:

- You want to sort or reorder your data.

- You need to align your data to another structure.

- You want to introduce missing entries (e.g., add new car models or months).

**How to use:**
- Use the reindex() method to perform reindexing.

- For rows: df.reindex(new_row_labels)

- For columns: df.reindex(columns=new_col_labels)

- For both: df.reindex(index=..., columns=...)

In [36]:
# let's reorder the rows
new_order = ['RAV4', 'Tacoma', 'Camry', 'Corolla', 'Prius', 'Highlander']
df_reordered = df.reindex(new_order)
print(df_reordered)

            Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
RAV4         35   33   30   28   36   34   32   38   37   39   40   42
Tacoma       20   22   21   19   23   25   24   22   23   25   26   27
Camry        15   18   16   20   22   21   19   17   18   22   24   26
Corolla      23   25   22   20   30   28   26   27   29   33   31   35
Prius        28   30   32   29   31   33   35   34   36   38   37   40
Highlander   12   15   14   13   16   18   17   14   15   16   18   19

**What happens:**

Rows are reordered according to new_order.

Data is preserved for existing labels.

If any label is missing in the original, Pandas will insert NaN.

In [38]:
# You can reindex with additional labels to introduce missing rows:
df_expanded = df.reindex(['RAV4', 'Tacoma', 'Yaris', 'Tundra'])
print(df_expanded)

         Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
RAV4    35.0  33.0  30.0  28.0  36.0  34.0  32.0  38.0  37.0  39.0  40.0  42.0
Tacoma  20.0  22.0  21.0  19.0  23.0  25.0  24.0  22.0  23.0  25.0  26.0  27.0
Yaris    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
Tundra   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

In [39]:
# reorder columns
month_order = ['Mar', 'Jan', 'Dec', 'Jun']
df_cols_reordered = df.reindex(columns=month_order)
print(df_cols_reordered)

            Mar  Jan  Dec  Jun
Corolla      22   23   35   28
Camry        16   15   26   21
RAV4         30   35   42   34
Highlander   14   12   19   18
Prius        32   28   40   33
Tacoma       21   20   27   25

In [40]:
#Reindex with Both Rows and Columns
df_custom = df.reindex(index=['Prius', 'Camry', 'Yaris'], columns=['Feb', 'Aug', 'Oct'])
print(df_custom)

        Feb   Aug   Oct
Prius  30.0  34.0  38.0
Camry  18.0  17.0  22.0
Yaris   NaN   NaN   NaN

### Dropping Entries ###

Dropping means removing rows or columns from a DataFrame. You can drop:

- One or more rows by label (e.g., a car model),

- One or more columns by label (e.g., a month),

- Temporarily (without modifying the original DataFrame), or permanently (by using inplace=True).

**How it works**

<pre>df.drop(labels, axis, inplace=True/False)</pre>

- labels: the names of rows or columns to drop

- axis=0: drop by row

- axis=1: drop by column

- inplace=True: apply changes directly to df (no need to assign, inplace=False (default): retruns a new df

In [43]:
# Drop a Single Row (e.g Camry)
df.drop('Camry') # axis=0 is default

            Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
Corolla      23   25   22   20   30   28   26   27   29   33   31   35
RAV4         35   33   30   28   36   34   32   38   37   39   40   42
Highlander   12   15   14   13   16   18   17   14   15   16   18   19
Prius        28   30   32   29   31   33   35   34   36   38   37   40
Tacoma       20   22   21   19   23   25   24   22   23   25   26   27

In [44]:
# Drop Multiple Rows
df.drop(['Camry', 'Tacoma'])

            Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
Corolla      23   25   22   20   30   28   26   27   29   33   31   35
RAV4         35   33   30   28   36   34   32   38   37   39   40   42
Highlander   12   15   14   13   16   18   17   14   15   16   18   19
Prius        28   30   32   29   31   33   35   34   36   38   37   40

In [45]:
#  Drop a Column (e.g Jan)
df.drop('Jan', axis=1)

            Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
Corolla      25   22   20   30   28   26   27   29   33   31   35
Camry        18   16   20   22   21   19   17   18   22   24   26
RAV4         33   30   28   36   34   32   38   37   39   40   42
Highlander   15   14   13   16   18   17   14   15   16   18   19
Prius        30   32   29   31   33   35   34   36   38   37   40
Tacoma       22   21   19   23   25   24   22   23   25   26   27

In [46]:
# drop multiple columns
df.drop(['Jan', 'Feb'], axis=1)

            Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
Corolla      22   20   30   28   26   27   29   33   31   35
Camry        16   20   22   21   19   17   18   22   24   26
RAV4         30   28   36   34   32   38   37   39   40   42
Highlander   14   13   16   18   17   14   15   16   18   19
Prius        32   29   31   33   35   34   36   38   37   40
Tacoma       21   19   23   25   24   22   23   25   26   27

**Drop with inplace=True (Destructive Operation use with caution)**

This modifies the original df and returns None.

Always use this cautiously or copy your data first.

In [48]:
df.drop('Camry', inplace=True)
print(df)

            Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
Corolla      23   25   22   20   30   28   26   27   29   33   31   35
RAV4         35   33   30   28   36   34   32   38   37   39   40   42
Highlander   12   15   14   13   16   18   17   14   15   16   18   19
Prius        28   30   32   29   31   33   35   34   36   38   37   40
Tacoma       20   22   21   19   23   25   24   22   23   25   26   27

### Arithmetic and Data Alignment ###

Pandas lets you perform arithmetic (addition, subtraction, etc.) between entire DataFrames or Series, while automatically matching rows and columns by their labels. This is called label-based alignment.

Even if DataFrames or Series are not the same shape, Pandas will align them based on their index and column names and fill in missing values with NaN.

**Basic Arithmetic with Scalars**

In [79]:
# Add 10 to every sales value
df_plus_10 = df + 10
print(df_plus_10)

            Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
Corolla      33   35   32   30   40   38   36   37   39   43   41   45
RAV4         45   43   40   38   46   44   42   48   47   49   50   52
Highlander   22   25   24   23   26   28   27   24   25   26   28   29
Prius        38   40   42   39   41   43   45   44   46   48   47   50
Tacoma       30   32   31   29   33   35   34   32   33   35   36   37

In [81]:
# Multiply all sales by 1.1 (e.g., apply a 10% price increase)
df_bonus = df * 1.1
print(df_bonus)

             Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov  \
Corolla     25.3  27.5  24.2  22.0  33.0  30.8  28.6  29.7  31.9  36.3  34.1
RAV4        38.5  36.3  33.0  30.8  39.6  37.4  35.2  41.8  40.7  42.9  44.0
Highlander  13.2  16.5  15.4  14.3  17.6  19.8  18.7  15.4  16.5  17.6  19.8
Prius       30.8  33.0  35.2  31.9  34.1  36.3  38.5  37.4  39.6  41.8  40.7
Tacoma      22.0  24.2  23.1  20.9  25.3  27.5  26.4  24.2  25.3  27.5  28.6

             Dec
Corolla     38.5
RAV4        46.2
Highlander  20.9
Prius       44.0
Tacoma      29.7

In [93]:
# Monthly average sales which is a series
monthly_avg = df.mean()

# Subtract average from each month's data (column-wise)
df_diff = df - monthly_avg
print(df_diff)

             Jan   Feb  Mar  Apr   May  Jun  Jul   Aug   Sep   Oct   Nov   Dec
Corolla     -0.6   0.0 -1.8 -1.8   2.8  0.4 -0.8   0.0   1.0   2.8   0.6   2.4
RAV4        11.4   8.0  6.2  6.2   8.8  6.4  5.2  11.0   9.0   8.8   9.6   9.4
Highlander -11.6 -10.0 -9.8 -8.8 -11.2 -9.6 -9.8 -13.0 -13.0 -14.2 -12.4 -13.6
Prius        4.4   5.0  8.2  7.2   3.8  5.4  8.2   7.0   8.0   7.8   6.6   7.4
Tacoma      -3.6  -3.0 -2.8 -2.8  -4.2 -2.6 -2.8  -5.0  -5.0  -5.2  -4.4  -5.6

**Use .add(), .sub(), .mul(), .div() with fill_value**

To prevent NaNs when labels are missing, use arithmetic methods with fill_value:

In [114]:
df1 = pd.DataFrame({'A': [1, 2]}, index=['X', 'Y'])
df2 = pd.DataFrame({'A': [3]}, index=['X'])

# Default behavior: Y becomes NaN
df1 + df2

# Safe addition with fill value 
df1.add(df2, fill_value=0) #try it without fill_value

     A
X  4.0
Y  2.0

### Applying Functions ###
Pandas gives you multiple ways to apply functions to your data, depending on whether you want to operate on:

- Whole rows or columns

- Each individual element

The .apply() method is used when you want to apply a function across each row or column.

The .apply() method expects to receive a function as its argument.

A function that takes either a Series (if used on a DataFrame) or a scalar (if used on a Series) and returns a value.

The function can be a
**built-in function**,
**user-defined function**,
or a **lambda function**

In [123]:
# built-in
print(df.apply(np.mean))        # applies to each column by default

Jan    23.6
Feb    25.0
Mar    23.8
Apr    21.8
May    27.2
Jun    27.6
Jul    26.8
Aug    27.0
Sep    28.0
Oct    30.2
Nov    30.4
Dec    32.6
dtype: float64

In [125]:
print(df.apply(np.sum, axis=1)) # applies to each row

Corolla       329
RAV4          424
Highlander    187
Prius         403
Tacoma        277
dtype: int64

In [127]:
# user-defined function
def range_func(x):
    return x.max() - x.min()

df_range = df.apply(range_func, axis=1)  # applies to each row
print(df_range)

Corolla       15
RAV4          14
Highlander     7
Prius         12
Tacoma         8
dtype: int64

In [133]:
# lambda
df.apply(lambda c: c.mean()) # column wise

Jan    23.6
Feb    25.0
Mar    23.8
Apr    21.8
May    27.2
Jun    27.6
Jul    26.8
Aug    27.0
Sep    28.0
Oct    30.2
Nov    30.4
Dec    32.6
dtype: float64

###  Mapping ###
.map() is used for element-wise transformations on Series. It's most useful when:

- You want to transform values based on rules

- You want to replace values based on a mapping

In [139]:
# Categorize Car Models by Performance

# Average sales per model
avg_sales = df.mean(axis=1)

# Map numeric average to label
categories = avg_sales.map(lambda x: 'High' if x > 30 else 'Low')
print(categories)

Corolla        Low
RAV4          High
Highlander     Low
Prius         High
Tacoma         Low
dtype: object